version: '3.8'

services:
  be:
    build: .
    container_name: aspira-be
    ports:
      - "8000:8000"
    environment:
      - CHANNEL_SECRET=${CHANNEL_SECRET}
      - CHANNEL_ACCESS_TOKEN=${CHANNEL_ACCESS_TOKEN}
    restart: unless-stopped