version: '3.8'

services:

  be:
    build: 
      context: ./be
    container_name: be
    ports:
      - "8000:8000"
    environment:
      - CHANNEL_SECRET=${CHANNEL_SECRET}
      - CHANNEL_ACCESS_TOKEN=${CHANNEL_ACCESS_TOKEN}
      - OLLAMA_URL=http://ollama:11434  # Internal Docker network URL
    restart: unless-stopped
    depends_on:
      - ollama
     
    

  ollama:
    build:
      context: ./ollama
    container_name: ollama
    ports:
      - "11434:11434"